using FRJ.Tools.SimpleWorkSheet.Examples.Examples.AdvancedExamples;
using FRJ.Tools.SimpleWorkSheet.Examples.Examples.BasicExamples;
using FRJ.Tools.SimpleWorkSheet.Examples.Examples.BatchExamples;
using FRJ.Tools.SimpleWorkSheet.Examples.Examples.CalibrationExamples;
using FRJ.Tools.SimpleWorkSheet.Examples.Examples.FormulaExamples;
using FRJ.Tools.SimpleWorkSheet.Examples.Examples.ImportExamples;
using FRJ.Tools.SimpleWorkSheet.Examples.Examples.IntegrationExamples;
using FRJ.Tools.SimpleWorkSheet.Examples.Examples.StylingExamples;

namespace FRJ.Tools.SimpleWorkSheet.Examples.Examples.Utils;

public static class ExampleRegistry
{
    public static Dictionary<Type, int> Numbers { get; } = new()
    {
        [typeof(HelloWorldExample)] = 1,
        [typeof(DataTypesExample)] = 2,
        [typeof(SimpleTableExample)] = 3,
        [typeof(CellPositioningExample)] = 4,
        [typeof(ValueOnlyExample)] = 5,
        [typeof(FontVariationsExample)] = 6,
        [typeof(BackgroundColorsExample)] = 7,
        [typeof(BorderStylesExample)] = 8,
        [typeof(CompleteStylingExample)] = 9,
        [typeof(RowAdditionExample)] = 10,
        [typeof(ColumnAdditionExample)] = 11,
        [typeof(BulkUpdatesExample)] = 12,
        [typeof(MetadataTrackingExample)] = 13,
        [typeof(ImportOptionsExample)] = 14,
        [typeof(CsvSimulationExample)] = 15,
        [typeof(ConditionalFormattingExample)] = 16,
        [typeof(ReusableStylesExample)] = 17,
        [typeof(ComplexTableExample)] = 18,
        [typeof(InvoiceGeneratorExample)] = 19,
        [typeof(DataVisualizationExample)] = 20,
        [typeof(BasicFormulasExample)] = 21,
        [typeof(SumFormulaExample)] = 22,
        [typeof(AverageFormulaExample)] = 23,
        [typeof(PercentageFormulaExample)] = 24,
        [typeof(ConditionalFormulaExample)] = 25,
        [typeof(MultiRangeFormulaExample)] = 26,
        [typeof(CountFormulaExample)] = 27,
        [typeof(MinMaxFormulaExample)] = 28,
        [typeof(JsonArrayImportExample)] = 29,
        [typeof(JsonSparseArrayImportExample)] = 30,
        [typeof(RowHeightExample)] = 31,
        [typeof(FreezePanesExample)] = 32,
        [typeof(TextAlignmentExample)] = 33,
        [typeof(HyperlinksExample)] = 34,
        [typeof(ReadExcelExample)] = 35,
        [typeof(RoundTripEditingExample)] = 36,
        [typeof(CellMergingExample)] = 37,
        [typeof(DataValidationExample)] = 38,
        [typeof(NamedRangesExample)] = 39,
        [typeof(AdvancedFormulasExample)] = 40,
        [typeof(BarChartExample)] = 41,
        [typeof(LineChartExample)] = 42,
        [typeof(PieChartExample)] = 43,
        [typeof(ScatterChartExample)] = 44,
        [typeof(ChartSheetExample)] = 45,
        [typeof(AutoFitColumnsExample)] = 46,
        [typeof(SheetTabColorsExample)] = 47,
        [typeof(SheetVisibilityExample)] = 48,
        [typeof(ExcelTablesExample)] = 49,
        [typeof(InsertImagesExample)] = 50,
        [typeof(AreaChartExample)] = 51,
        [typeof(StackedAreaChartExample)] = 52,
        [typeof(ChartFormattingExample)] = 53,
        [typeof(JsonFluentImportPricesExample)] = 54,
        [typeof(JsonFluentImportPricesFlatExample)] = 55,
        [typeof(JsonFluentImportPersonsExample)] = 56,
        [typeof(JsonArrayWithStylingExample)] = 57,
        [typeof(JsonFlatObjectWithParsersExample)] = 58,
        [typeof(JsonMultiColumnAllFeaturesExample)] = 59,
        [typeof(JsonNestedObjectsExample)] = 60,
        [typeof(JsonToWorkbookExample)] = 61,
        [typeof(JsonToWorkbookLineChartExample)] = 62,
        [typeof(JsonToWorkbookBarChartExample)] = 63,
        [typeof(JsonToWorkbookMultipleChartsExample)] = 64,
        [typeof(JsonColumnOrderingExample)] = 65,
        [typeof(JsonColumnFilteringExample)] = 66,
        [typeof(JsonDateNumberFormattingExample)] = 67,
        [typeof(JsonConditionalStylingExample)] = 68,
        [typeof(JsonAdvancedWorkbookExample)] = 69,
        [typeof(CsvWithHeaderExample)] = 70,
        [typeof(CsvWithoutHeaderExample)] = 71,
        [typeof(CsvAdvancedFeaturesExample)] = 72,
        [typeof(CsvToWorkbookWithChartExample)] = 73,
        [typeof(GenericTableBasicExample)] = 74,
        [typeof(GenericTableAdvancedExample)] = 75,
        [typeof(GenericTableToWorkbookExample)] = 76,
        [typeof(GenericTableWorkbookAdvancedExample)] = 77,
        [typeof(BuiltInColorsExample)] = 78,
        [typeof(ClassToWorkbookExample)] = 79,
        [typeof(ChartSeriesNamesImportAutoExample)] = 80,
        [typeof(ChartSeriesNamesImportCustomExample)] = 81,
        [typeof(ChartSeriesNamesImportCsvExample)] = 82,
        [typeof(ChartSeriesNamesImportGenericTableExample)] = 83,
        [typeof(ChartSeriesNamesExample)] = 84,
        [typeof(MultiTableMultiChartCommonSheetExample)] = 85,
        [typeof(ColumnHidingExample)] = 86,
        [typeof(RowHidingExample)] = 87,
        [typeof(ConditionalHidingExample)] = 88,
        [typeof(LineChartMultipleSeriesExample)] = 89,
        [typeof(LineChartWithoutCategoriesExample)] = 90,
        [typeof(LineChartMultipleSeriesWithoutCategoriesExample)] = 91,
        [typeof(BarChartWithoutCategoriesExample)] = 92,
        [typeof(AreaChartWithoutCategoriesExample)] = 93,
        [typeof(LineChartWithDataLabelsExample)] = 94,
        [typeof(LineChartMultipleSeriesWithDataLabelsExample)] = 95,
        [typeof(ScatterChartWithDataLabelsExample)] = 96,
        [typeof(LineChartWithYAxisLabelsExample)] = 97,
        [typeof(LineChartMultipleSeriesWithYAxisLabelsExample)] = 98,
        [typeof(ScatterChartWithYAxisLabelsExample)] = 99,
        [typeof(LineChartWithoutYAxisLabelsExample)] = 100,
        [typeof(BarChartWithoutYAxisLabelsExample)] = 101,
        [typeof(AreaChartWithoutYAxisLabelsExample)] = 102,
        [typeof(LineChartWithCustomColorExample)] = 103,
        [typeof(LineChartMultipleSeriesWithColorsExample)] = 104,
        [typeof(BarChartWithCustomColorsExample)] = 105,
        [typeof(AreaChartWithCustomColorsExample)] = 106,
        [typeof(ChartColorPaletteExample)] = 107,
        [typeof(EnvironmentSheetInfoExample)] = 108,
        [typeof(SimpleCalibrationWorkbookDefaultExample)] = 109,
        [typeof(SimpleCalibrationWorkbook09Example)] = 110,
        [typeof(SimpleCalibrationWorkbook11Example)] = 111,
        [typeof(AutoFitColumnsBaselineExample)] = 112
    };
}
